/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <Android/bitmap.h>
#include <Android/log.h>
#include <stdlib.h>
#include <math.h>
/* Header for class com_xinlan_imageprocess_NativeLib */

#ifndef _Included_com_xinlan_imageprocess_NativeLib
#define _Included_com_xinlan_imageprocess_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xinlan_imageprocess_NativeLib
 * Method:    process
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT
void JNICALL Java_com_xinlan_imageprocess_NativeLib_process
  (JNIEnv *, jclass, jobject ,jint ,jint );

#ifdef __cplusplus
}
#endif
#endif
